// Minimal Next.js 15 + Tailwind scaffold for downloadable generated sites.
// The generated page body is injected into src/app/page.tsx.
// User runs `npm install && npm run dev` and gets a working site.

export type ScaffoldInput = {
  brandName: string;
  accent: string;
  pageContent: string; // Full JSX body inside the exported default component
};

function sanitizeBrand(name: string): string {
  return (
    name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "") || "site"
  );
}

export function buildScaffoldFiles(input: ScaffoldInput): Record<string, string> {
  const slug = sanitizeBrand(input.brandName);
  const files: Record<string, string> = {};

  files["package.json"] = JSON.stringify(
    {
      name: slug,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
        lint: "next lint",
      },
      dependencies: {
        next: "15.1.0",
        react: "19.0.0",
        "react-dom": "19.0.0",
      },
      devDependencies: {
        "@types/node": "^20",
        "@types/react": "^19",
        "@types/react-dom": "^19",
        autoprefixer: "^10",
        postcss: "^8",
        tailwindcss: "^3.4.17",
        typescript: "^5",
      },
    },
    null,
    2
  );

  files["next.config.js"] = `/** @type {import('next').NextConfig} */
const nextConfig = {};
module.exports = nextConfig;
`;

  files["tsconfig.json"] = JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
      exclude: ["node_modules"],
    },
    null,
    2
  );

  files["tailwind.config.ts"] = `import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        accent: "${input.accent}",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["'Space Grotesk'", "Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
`;

  files["postcss.config.js"] = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;

  files["src/app/globals.css"] = `@tailwind base;
@tailwind components;
@tailwind utilities;

@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap');

html, body {
  background: #0a0a0b;
  color: #f4f4f5;
  -webkit-font-smoothing: antialiased;
}

::selection {
  background: ${input.accent};
  color: #0a0a0b;
}
`;

  files["src/app/layout.tsx"] = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${input.brandName}",
  description: "${input.brandName} — premium experience",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="nl">
      <body className="font-sans antialiased">{children}</body>
    </html>
  );
}
`;

  files["src/app/page.tsx"] = `export default function Page() {
${input.pageContent}
}
`;

  files["README.md"] = `# ${input.brandName}

Generated by Autronis Site Rebuild.

## Development

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).

## Deployment

Push to GitHub and import into Vercel — zero config.
`;

  files[".gitignore"] = `node_modules
.next
.env.local
dist
`;

  return files;
}
