// src/lib/proposal-pdf/styles.ts
import { StyleSheet } from "@react-pdf/renderer";
import { DECK_COLORS, DECK_SIZES } from "@/lib/proposal-deck-tokens";

export const pdfStyles = StyleSheet.create({
  page: {
    backgroundColor: DECK_COLORS.bg,
    color: DECK_COLORS.textPrimary,
    padding: 60,
    fontFamily: "Inter",
    fontSize: DECK_SIZES.pdfBody,
  },
  absoluteFill: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: DECK_COLORS.overlayDark,
  },
  content: {
    flex: 1,
    justifyContent: "center",
  },
  typeLabel: {
    fontFamily: "Inter",
    fontSize: 9,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: DECK_COLORS.accent,
    fontWeight: 600,
    marginBottom: 16,
  },
  headingXL: {
    fontFamily: "SpaceGrotesk",
    fontSize: DECK_SIZES.pdfCoverHeading,
    fontWeight: 700,
    color: DECK_COLORS.textPrimary,
    lineHeight: 1,
  },
  headingLG: {
    fontFamily: "SpaceGrotesk",
    fontSize: DECK_SIZES.pdfHeading,
    fontWeight: 700,
    color: DECK_COLORS.textPrimary,
    lineHeight: 1.1,
  },
  subheading: {
    fontFamily: "Inter",
    fontSize: DECK_SIZES.pdfSubheading,
    color: DECK_COLORS.accent,
    lineHeight: 1.3,
    marginTop: 16,
  },
  body: {
    fontFamily: "Inter",
    fontSize: DECK_SIZES.pdfBody,
    color: DECK_COLORS.textPrimary,
    lineHeight: 1.5,
    opacity: 0.9,
  },
  small: {
    fontFamily: "Inter",
    fontSize: DECK_SIZES.pdfSmall,
    color: DECK_COLORS.textSecondary,
  },
  accent: {
    color: DECK_COLORS.accent,
  },
  bulletRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 14,
    gap: 16,
  },
  bulletNumber: {
    fontFamily: "SpaceGrotesk",
    fontSize: 22,
    fontWeight: 700,
    color: DECK_COLORS.accent,
    minWidth: 36,
  },
  bulletText: {
    fontFamily: "Inter",
    fontSize: 16,
    color: DECK_COLORS.textPrimary,
    flex: 1,
    lineHeight: 1.4,
  },
  faseCard: {
    borderWidth: 1,
    borderColor: DECK_COLORS.border,
    borderRadius: 12,
    padding: 14,
    backgroundColor: DECK_COLORS.card,
  },
  faseCardHeader: {
    fontFamily: "SpaceGrotesk",
    fontSize: 9,
    fontWeight: 700,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: DECK_COLORS.accent,
    marginBottom: 6,
  },
  faseCardTitle: {
    fontFamily: "Inter",
    fontSize: 14,
    fontWeight: 600,
    color: DECK_COLORS.textPrimary,
    marginBottom: 6,
  },
  faseCardBody: {
    fontFamily: "Inter",
    fontSize: 10,
    color: DECK_COLORS.textSecondary,
    lineHeight: 1.4,
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: DECK_COLORS.border,
    paddingVertical: 8,
  },
  totaalImpact: {
    fontFamily: "SpaceGrotesk",
    fontSize: DECK_SIZES.pdfTotaalImpact,
    fontWeight: 700,
    color: DECK_COLORS.accent,
    lineHeight: 1,
  },
});
