/* eslint-disable no-console */
import { config } from "dotenv";
config({ path: ".env.local" });
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { db } = require("../src/lib/db");
// eslint-disable-next-line @typescript-eslint/no-require-imports
const schema = require("../src/lib/db/schema");
import { like } from "drizzle-orm";

const now = new Date();
const minsAgo = (m: number) => new Date(now.getTime() - m * 60_000).toISOString();

const rows = [
  {
    jobId: "mock-001",
    url: "https://www.upwork.com/jobs/~mock001",
    titel: "n8n workflow for Shopify → Notion order sync",
    beschrijving:
      "We run a Shopify store and want incoming orders automatically surfaced in Notion with enriched customer history. Need: n8n workflow, error retries, Slack alert on failure. Familiarity with Shopify webhooks a must.",
    budgetType: "fixed" as const,
    budgetMin: 800,
    budgetMax: 1200,
    budgetTier: "mid" as const,
    country: "United States",
    postedAt: minsAgo(14),
    durationEstimate: "1 to 3 months",
    experienceLevel: "Intermediate",
    categoryLabels: JSON.stringify(["Web Development", "Automation"]),
    clientNaam: "Brookside Coffee Co.",
    clientVerified: 1,
    clientSpent: 12400,
    clientHireRate: 78,
    clientReviews: 23,
    clientRating: 4.8,
    screeningQs: JSON.stringify([
      "Heb je ervaring met Shopify webhooks?",
      "Hoeveel n8n workflows heb je in productie staan?",
    ]),
    proposalsRangeMin: 5,
    proposalsRangeMax: 10,
    seenBy: JSON.stringify(["sem"]),
    status: "new",
    aangemaaktOp: minsAgo(14),
    bijgewerktOp: minsAgo(14),
  },
  {
    jobId: "mock-002",
    url: "https://www.upwork.com/jobs/~mock002",
    titel: "Claude-powered customer support triage agent",
    beschrijving:
      "Looking for a developer to build an AI agent using Claude that reads incoming Zendesk tickets, classifies priority/category, drafts a reply, and assigns to the right team. Must handle 500+ tickets/day.",
    budgetType: "hourly" as const,
    budgetMin: 75,
    budgetMax: 120,
    budgetTier: "premium" as const,
    country: "United Kingdom",
    postedAt: minsAgo(42),
    durationEstimate: "3 to 6 months",
    experienceLevel: "Expert",
    categoryLabels: JSON.stringify(["AI Development", "Automation"]),
    clientNaam: "Nordic Labs Ltd.",
    clientVerified: 1,
    clientSpent: 87300,
    clientHireRate: 92,
    clientReviews: 41,
    clientRating: 4.95,
    screeningQs: JSON.stringify([
      "Link naar een deployed Claude agent",
      "Hoe ga je om met hallucination in customer-facing replies?",
    ]),
    proposalsRangeMin: 10,
    proposalsRangeMax: 15,
    seenBy: JSON.stringify(["sem", "syb"]),
    status: "new",
    aangemaaktOp: minsAgo(42),
    bijgewerktOp: minsAgo(42),
  },
  {
    jobId: "mock-003",
    url: "https://www.upwork.com/jobs/~mock003",
    titel: "Next.js + Supabase dashboard for SaaS metrics",
    beschrijving:
      "Build internal dashboard: revenue chart, cohort retention, churn analysis. Data in Supabase, want realtime updates. Dark theme, mobile responsive.",
    budgetType: "fixed" as const,
    budgetMin: 3500,
    budgetMax: null,
    budgetTier: "premium" as const,
    country: "Netherlands",
    postedAt: minsAgo(95),
    durationEstimate: "Less than 1 month",
    experienceLevel: "Expert",
    categoryLabels: JSON.stringify(["Web Development", "Data Visualization"]),
    clientNaam: "FlowMetric BV",
    clientVerified: 1,
    clientSpent: 4200,
    clientHireRate: 100,
    clientReviews: 3,
    clientRating: 5.0,
    screeningQs: null,
    proposalsRangeMin: 15,
    proposalsRangeMax: 20,
    seenBy: JSON.stringify(["syb"]),
    status: "new",
    aangemaaktOp: minsAgo(95),
    bijgewerktOp: minsAgo(95),
  },
  {
    jobId: "mock-004",
    url: "https://www.upwork.com/jobs/~mock004",
    titel: "Web scraper for competitor pricing (Python)",
    beschrijving:
      "Need a scraper that pulls product prices from 12 competitor sites daily. Python, BeautifulSoup/Playwright, store in Postgres. Should handle rate limits gracefully.",
    budgetType: "fixed" as const,
    budgetMin: 350,
    budgetMax: 500,
    budgetTier: "low" as const,
    country: "Canada",
    postedAt: minsAgo(180),
    durationEstimate: "Less than 1 month",
    experienceLevel: "Intermediate",
    categoryLabels: JSON.stringify(["Web Scraping", "Python"]),
    clientNaam: "PriceWise Analytics",
    clientVerified: 0,
    clientSpent: 320,
    clientHireRate: 50,
    clientReviews: 2,
    clientRating: 3.8,
    screeningQs: JSON.stringify(["Laat een scraper portfolio item zien"]),
    proposalsRangeMin: 20,
    proposalsRangeMax: 50,
    seenBy: JSON.stringify(["sem"]),
    status: "new",
    aangemaaktOp: minsAgo(180),
    bijgewerktOp: minsAgo(180),
  },
  {
    jobId: "mock-005",
    url: "https://www.upwork.com/jobs/~mock005",
    titel: "OpenAI to Claude migration for existing agents",
    beschrijving:
      "We have 6 production agents running on GPT-4. Want to migrate to Claude 4.7 Sonnet. Need prompt tuning, tool-use parity verification, and a regression test suite.",
    budgetType: "hourly" as const,
    budgetMin: 60,
    budgetMax: 90,
    budgetTier: "mid" as const,
    country: "Germany",
    postedAt: minsAgo(240),
    durationEstimate: "1 to 3 months",
    experienceLevel: "Expert",
    categoryLabels: JSON.stringify(["AI Development", "Prompt Engineering"]),
    clientNaam: "Helix Automation GmbH",
    clientVerified: 1,
    clientSpent: 28900,
    clientHireRate: 85,
    clientReviews: 14,
    clientRating: 4.7,
    screeningQs: JSON.stringify([
      "Heb je Claude 4.x tool use in productie?",
      "Hoe test je hallucination regressie?",
    ]),
    proposalsRangeMin: 5,
    proposalsRangeMax: 10,
    seenBy: JSON.stringify(["sem", "syb"]),
    claimedBy: "sem",
    claimedAt: minsAgo(210),
    status: "claimed",
    aangemaaktOp: minsAgo(240),
    bijgewerktOp: minsAgo(210),
  },
  {
    jobId: "mock-006",
    url: "https://www.upwork.com/jobs/~mock006",
    titel: "AI automation for real estate lead qualification",
    beschrijving:
      "Incoming leads via web form → AI qualifies intent → routes hot leads to sales team. Want it built on n8n + Claude. Must integrate with Pipedrive.",
    budgetType: "fixed" as const,
    budgetMin: 1800,
    budgetMax: 2500,
    budgetTier: "mid" as const,
    country: "Australia",
    postedAt: minsAgo(320),
    durationEstimate: "1 to 3 months",
    experienceLevel: "Intermediate",
    categoryLabels: JSON.stringify(["AI Development", "Automation", "CRM"]),
    clientNaam: "Sunrise Realty Group",
    clientVerified: 1,
    clientSpent: 5400,
    clientHireRate: 67,
    clientReviews: 6,
    clientRating: 4.3,
    screeningQs: JSON.stringify([
      "Eerdere real estate ervaring?",
      "Hoe borg je AI output kwaliteit?",
    ]),
    proposalsRangeMin: 10,
    proposalsRangeMax: 15,
    seenBy: JSON.stringify(["syb"]),
    status: "new",
    aangemaaktOp: minsAgo(320),
    bijgewerktOp: minsAgo(320),
  },
  {
    jobId: "mock-007",
    url: "https://www.upwork.com/jobs/~mock007",
    titel: "Data pipeline: API → Snowflake with dbt",
    beschrijving:
      "Ingest 15 SaaS APIs into Snowflake daily via Fivetran + custom Python. Transform with dbt. Documentation + tests required.",
    budgetType: "hourly" as const,
    budgetMin: 55,
    budgetMax: null,
    budgetTier: "mid" as const,
    country: "United States",
    postedAt: minsAgo(480),
    durationEstimate: "3 to 6 months",
    experienceLevel: "Expert",
    categoryLabels: JSON.stringify(["Data Engineering"]),
    clientNaam: "Meridian Capital",
    clientVerified: 1,
    clientSpent: 142000,
    clientHireRate: 88,
    clientReviews: 67,
    clientRating: 4.9,
    screeningQs: null,
    proposalsRangeMin: 20,
    proposalsRangeMax: 50,
    seenBy: JSON.stringify(["sem"]),
    status: "new",
    aangemaaktOp: minsAgo(480),
    bijgewerktOp: minsAgo(480),
  },
  {
    jobId: "mock-008",
    url: "https://www.upwork.com/jobs/~mock008",
    titel: "Quick bug fix: Zapier workflow intermittently fails",
    beschrijving:
      "Zapier flow between Stripe → Google Sheets drops ~5% of events. Need someone to diagnose + fix.",
    budgetType: "fixed" as const,
    budgetMin: 150,
    budgetMax: null,
    budgetTier: "low" as const,
    country: "India",
    postedAt: minsAgo(620),
    durationEstimate: "Less than 1 month",
    experienceLevel: "Entry",
    categoryLabels: JSON.stringify(["Automation"]),
    clientNaam: "Pratap Ventures",
    clientVerified: 0,
    clientSpent: 0,
    clientHireRate: null,
    clientReviews: 0,
    clientRating: null,
    screeningQs: null,
    proposalsRangeMin: 50,
    proposalsRangeMax: 100,
    seenBy: JSON.stringify(["sem", "syb"]),
    status: "new",
    aangemaaktOp: minsAgo(620),
    bijgewerktOp: minsAgo(620),
  },
  {
    jobId: "mock-009",
    url: "https://www.upwork.com/jobs/~mock009",
    titel: "Chatbot for SaaS onboarding (React + Claude)",
    beschrijving:
      "In-app chatbot that guides new users through product setup. Uses Claude for natural conversation + tool-use for in-app actions (create project, invite teammate).",
    budgetType: "fixed" as const,
    budgetMin: 4200,
    budgetMax: 6000,
    budgetTier: "premium" as const,
    country: "Sweden",
    postedAt: minsAgo(840),
    durationEstimate: "1 to 3 months",
    experienceLevel: "Expert",
    categoryLabels: JSON.stringify(["AI Development", "React"]),
    clientNaam: "Lumen Analytics AB",
    clientVerified: 1,
    clientSpent: 34500,
    clientHireRate: 95,
    clientReviews: 12,
    clientRating: 4.9,
    screeningQs: JSON.stringify([
      "Link naar live chatbot die je hebt gebouwd",
      "Hoe monitor je tool-use errors?",
    ]),
    proposalsRangeMin: 10,
    proposalsRangeMax: 15,
    seenBy: JSON.stringify(["sem", "syb"]),
    status: "new",
    aangemaaktOp: minsAgo(840),
    bijgewerktOp: minsAgo(840),
  },
  {
    jobId: "mock-010",
    url: "https://www.upwork.com/jobs/~mock010",
    titel: "Generic backend developer needed",
    beschrijving: null,
    budgetType: null,
    budgetMin: null,
    budgetMax: null,
    budgetTier: null,
    country: null,
    postedAt: minsAgo(55),
    durationEstimate: null,
    experienceLevel: null,
    categoryLabels: null,
    clientNaam: null,
    clientVerified: null,
    clientSpent: null,
    clientHireRate: null,
    clientReviews: null,
    clientRating: null,
    screeningQs: null,
    proposalsRangeMin: null,
    proposalsRangeMax: null,
    seenBy: JSON.stringify(["sem"]),
    status: "session_expired",
    fetchError: "Session cookie expired — run npm run upwork:login -- sem",
    aangemaaktOp: minsAgo(55),
    bijgewerktOp: minsAgo(55),
  },
];

async function main() {
  console.log(`Wissen van bestaande mock rows (jobId LIKE 'mock-%')...`);
  const deleted = await db
    .delete(schema.upworkJobs)
    .where(like(schema.upworkJobs.jobId, "mock-%"))
    .run();
  console.log(`${deleted.changes ?? 0} bestaande mock rows verwijderd.`);

  console.log(`Inserten van ${rows.length} mock rows...`);
  for (const r of rows) {
    await db.insert(schema.upworkJobs).values(r).run();
  }
  console.log(`Done. Open https://dashboard.autronis.nl/upwork`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
